
-- Table for USSD customers
CREATE TABLE USSD_CUSTOMER (
    MSISDN VARCHAR(20) PRIMARY KEY,
    PIN_HASH VARCHAR(255),
    PIN_RETRIES INT DEFAULT 0,
    LOCKED CHAR(1) DEFAULT 'N',
    FIRST_NAME VARCHAR(100),
    MIDDLE_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    PIN_PLAIN VARCHAR(100),
    SECRET_WORD VARCHAR(100)

);
CREATE TABLE USSD_SCREEN (
    SCREEN_CODE    VARCHAR(50) PRIMARY KEY,
    SCREEN_TEXT    VARCHAR(2000),
    INPUT_TYPE     VARCHAR(20),     -- NONE, OPTION, NUMBER, PIN, TEXT
    STORE_KEY      VARCHAR(50),
    ACTION_BEAN    VARCHAR(100),
    REQUIRES_AUTH  CHAR(1),
    IS_TERMINAL    CHAR(1)
);
CREATE TABLE USSD_TRANSITION (
    ID BIGINT PRIMARY KEY,
    FROM_SCREEN VARCHAR(50),
    INPUT_VALUE VARCHAR(20),        -- 1, 0, *, null
    TO_SCREEN VARCHAR(50),
    PRIORITY INT DEFAULT 0
);
