-- Table for USSD menus
CREATE TABLE USSD_MENU (
    ID BIGINT PRIMARY KEY,
    MENU_CODE VARCHAR(50) UNIQUE,
    MENU_TEXT VARCHAR(2000),
    PARENT_MENU VARCHAR(50),
    OPTION_VALUE VARCHAR(10),
    NEXT_MENU VARCHAR(50),
    IS_TERMINAL CHAR(1),
    REQUIRES_AUTH CHAR(1),
    ACTION_BEAN VARCHAR(100),
    INPUT_TYPE VARCHAR(30),
    STORE_KEY  VARCHAR(50)
);

-- Table for USSD customers
CREATE TABLE USSD_CUSTOMER (
    MSISDN VARCHAR(20) PRIMARY KEY,
    PIN_HASH VARCHAR(255),
    PIN_RETRIES INT DEFAULT 0,
    LOCKED CHAR(1) DEFAULT 'N',
    FIRST_NAME VARCHAR(100),
    MIDDLE_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    PIN_PLAIN VARCHAR(100)

);
